services:
  - type: web
    name: bar-app-web
    env: python
    buildCommand: npm install && npx tailwindcss -i ./app/static/css/input.css -o ./app/static/css/output.css --minify && pip install -r requirements.txt
    # ✅ CORRECCIÓN: Se cambia el comando de inicio para usar 'eventlet'
    startCommand: gunicorn -k eventlet -w 1 run:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true