"""Add annulled_cash_sales to CashSession

Revision ID: 34fba3506796
Revises: 95da1fc7d201
Create Date: 2025-08-14 01:11:25.393853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fba3506796'
down_revision = '95da1fc7d201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annulled_cash_sales', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_session', schema=None) as batch_op:
        batch_op.drop_column('annulled_cash_sales')

    # ### end Alembic commands ###
