"""Add status to OrderItem and new Cocina role

Revision ID: 462189745cab
Revises: 62494b6095fd
Create Date: 2025-10-13 11:07:43.483011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462189745cab'
down_revision = '62494b6095fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_type_name', ['type', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_type'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index('idx_product_type_name')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
