"""Add display_name and enhance reports

Revision ID: 71e2b4ff83f4
Revises: 463d592552ae
Create Date: 2025-08-09 15:21:31.403753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e2b4ff83f4'
down_revision = '463d592552ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
