"""Add CashSession model

Revision ID: 95da1fc7d201
Revises: b4cd6898a227
Create Date: 2025-08-12 14:29:32.749562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95da1fc7d201'
down_revision = '01334c14ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('counted_cash', sa.Float(), nullable=True),
    sa.Column('cash_sales', sa.Float(), nullable=True),
    sa.Column('card_sales', sa.Float(), nullable=True),
    sa.Column('transfer_sales', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('expected_cash', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_session')
    # ### end Alembic commands ###
